### ISSUE TITLE
Sorting Algorithms

### ISSUE THREAD

**Issue by swaroop-2021** [Rough4993/DataStructure#7]
I want to add the following sorting algorithms in c++ language,

1) Bubble Sort
2) Selection Sort
3) Insertion Sort

Please Assign me this issue and add the hacktoberfest2023 tags, I am interested to Contribute : )

**Comment by ankitmwd01** [comment]
please assign me this task

**Comment by TanushreeBorase** [comment]
I would like to add the code for insertion sort , can u assign me this under hacktoberfest2023?
